Add rejection sampling script
allenai/open-instruct pull request #205
Opened 2024-07-26 18:56 UTC by vwxyzjn

2024-08-07 21:46 UTC, natolambert requested changes
Some high level comments on organization + long term management. 
* Where should we put this directory? 
* Is it good to be separated? Should this live in `open_instruct/*`
* Should add `rejection_sampling/` dir to makefile for style + add license to the top (make it 1st part). If not, we should add a "work in progress" tag to the top of the readme.
* Some comments / TODOs to remove

2024-08-07 21:46 UTC, natolambert commented on mason.py
Why is this called `mason.py`?

2024-08-07 21:46 UTC, natolambert commented on rejection_sampling/generation.py
> +def main(args: Args, dataset_args: DatasetArgs, gen_args: GenerationArgs):
I see why you made that minor change in the other PR.

2024-08-07 21:46 UTC, natolambert commented on rejection_sampling/generation.py
> +        # TODO: filter out duplicate messages ?
Remove comment or done :)

2024-08-08 14:45 UTC, vwxyzjn commented on rejection_sampling/generation.py
> +        # TODO: filter out duplicate messages ?
just implemented it

2024-08-08 14:45 UTC, vwxyzjn commented on mason.py
Taken from https://github.com/allenai/mason/tree/main/mason. I had to make some modification to it

2024-08-08 14:51 UTC, vwxyzjn commented
Thanks for the review @natolambert, I have moved the script to `open_instruct` and also the bash script to `scripts` folder, which should make more sense.

2024-08-08 15:49 UTC, natolambert reviewed
@vwxyzjn were the files `gpt_eval_judge.py` and `gpt_eval_judge1.py` added by mistake?

2024-08-08 16:03 UTC, vwxyzjn commented
Yeah that was added by mistake. I added a note on `mason.py`

2024-08-08 21:10 UTC, natolambert approved these changes

2024-08-08 21:22 UTC, merged