Fix the number of completions generation by OpenAI API
allenai/open-instruct pull request #260
Opened 2024-08-14 19:29 UTC by nouhadziri

This PR addresses two issues: it enables generating multiple completions from OpenAI and ensures that duplicate completions are skipped.

2024-08-14 20:16 UTC, vwxyzjn commented
Do you want to rebase main? The files tab is showing a changes that have already happened.
<img width="747" alt="image" src="https://github.com/user-attachments/assets/23f8419b-53d7-40c4-b319-99bf2c69c361">

2024-08-14 22:03 UTC, nouhadziri commented
Would it be possible if you do it? I'm afraid to mess up things 🙈

2024-08-15 16:08 UTC, vwxyzjn commented
Sure np let me take a look

2024-08-15 16:24 UTC, vwxyzjn commented
I went ahead and fixed the merge conflicts and now doing some testing

2024-08-15 16:37 UTC, vwxyzjn requested changes
When running

```
python open_instruct/rejection_sampling.py \
    --input_filename output/completions.jsonl \
    --model_names_or_paths gpt-4 \
    --save_filename output/rejection_sampled_completions.jsonl \
    --num_completions 3 \
    --push_to_hub \
    --num_gpus 1
```

I got 

<img width="858" alt="image" src="https://github.com/user-attachments/assets/02691871-0124-4f9a-9417-52eb7332cd4c">



Could you investigate what went wrong? I noticed the reference completions are still judged multiple times. Could you point me to the logic to remove duplicate completions for reference completion judging?

<img width="444" alt="image" src="https://github.com/user-attachments/assets/95e97013-e865-448c-8d16-08fcd0ca087a">


When you run the RM script, it should give output like

processing: 0:64/216
processing: 64:128/216
processing: 128:192/216
processing: 192:256/216
processing: 0:64/72
processing: 64:128/72

Notice the 216 is the 3 completions per prompt, and the 72 is the reference completion for RM judges. Similarly, there should only be 72 requests to LLM as a judge for reference completions.

2024-08-15 16:37 UTC, vwxyzjn commented on open_instruct/rejection_sampling/api_generate.py
> +    num_completions: int = 64
I like the name changes! To be more consistent with the codebase, I changed it to `num_completions`

2024-08-15 16:37 UTC, vwxyzjn commented on open_instruct/rejection_sampling/api_generate.py
> +    async def process_text(self, data: dict, i: int, limiter: asyncio.Semaphore, args: Args, gen_args: Args):
Very nice addition.

2024-08-16 00:17 UTC, nouhadziri reviewed
Thanks Costa for reviewing this and investigating the bug, could you approve this and I merge it? Thanks!

2024-08-16 00:19 UTC, vwxyzjn approved these changes
Thanks @nouhadziri! I am doing some final testing and will merge after this.

2024-08-16 00:19 UTC, vwxyzjn commented on open_instruct/rejection_sampling/generation.py
> +        print(f"Filtered out {prompt_token_ids_len - len(prompt_token_ids)} prompts which exceeds max token length")
@jacob-morrison this is for you :D

2024-08-16 00:26 UTC, nouhadziri commented on open_instruct/rejection_sampling/generation.py
> +        print(f"Filtered out {prompt_token_ids_len - len(prompt_token_ids)} prompts which exceeds max token length")
Wonderful, thank you!!!

2024-08-16 00:40 UTC, vwxyzjn commented
on jupiter https://beaker.org/ex/01J5C9BXR8MY9292734N4S84DA

on nfs https://beaker.org/ex/01J5C9BXR8MY9292734N4S84DA

all pass.

2024-08-16 00:40 UTC, merged