initial persona data gen 2 commit
allenai/open-instruct pull request #489
Opened 2024-12-18 22:47 UTC by fabrahman

This is the main scripts for persona-driven synthetic data generation for Math, Coding and Precise Instruction Following.

2024-12-18 23:44 UTC, natolambert requested changes
This looks good. Can we just host the jsonl files on huggingface or something so we don't need to add 200k lines of code to the repo?

2024-12-19 00:26 UTC, fabrahman commented
@natolambert good idea! removed the big files and moved them to hugging face dataset at: `ai2-adapt-dev/personahub_personas`

2024-12-19 14:53 UTC, vwxyzjn commented on scripts/persona_driven_data_gen/README.md
> +To start make sure you have your OpenAI and Anthropic API keys and have installed the libraries listed in `requirements.txt`:
Maybe give it a title like 


# Persona Data Generation

This folder contains scripts on generating persona data used for preference tuning in the Tulu 3 recipe [citation, section xxxx)

2024-12-19 14:53 UTC, vwxyzjn commented on scripts/persona_driven_data_gen/README.md
> +python persona_driven_generate_ifdata.py --model "gpt-4o" --start_index 0 --end_index <SAMPLE_SIZE> --output_path if_prompts.jsonl --openai_key Z --org_id YYY --dataset ai2-adapt-dev/personahub_perso
can we make the command copy-paste and run? E.g., remove `<SAMPLE_SIZE>` and replace it with a sensible default value. `--openai_key` should be read from the environment possibly? What is this `--org_id`?

2024-12-19 14:53 UTC, vwxyzjn commented on scripts/persona_driven_data_gen/README.md
> +python persona_driven_generate_ifdata.py --model "gpt-4o" --start_index 0 --end_index <SAMPLE_SIZE> --output_path if_solutions.jsonl --openai_key Z --org_id YYY --dataset if_prompts.jsonl --template
Maybe include some example outputs to give the readers on what to expect after running the script. Kind of like how I included `Here is an example created dataset: https://huggingface.co/datasets/vwxyzjn/rejection_sampling_1727887719` in  https://github.com/allenai/open-instruct/blob/main/docs/algorithms/rejection_sampling.md#scoring-completions

2025-01-01 22:10 UTC, fabrahman commented
@vwxyzjn Addressed the urgent comments. Could you please review and merge?

2025-01-03 18:00 UTC, fabrahman commented
@natolambert Addressed you requested changes. Could you pls review and merge this PR?

2025-01-06 02:36 UTC, vwxyzjn approved these changes

2025-01-06 02:37 UTC, vwxyzjn commented
Thanks @fabrahman!

2025-01-06 02:37 UTC, merged